### ISSUE TITLE
Windows ARM support

### ISSUE THREAD

**Issue by austinvazquez** [awslabs/amazon-ecr-credential-helper#795]
This is a tracking issue for Amazon ECR credential helper Windows ARM support.

```[tasklist]
### Tasks
- [x] Add variant to `all-variants` target
- [x] Release Windows ARM executables as experimental
- [ ] Run unit tests in GitHub Actions CI
- [ ] Run integration tests in CodeBuild
- [ ] Release Windows ARM executables as stable
```

**Comment by austinvazquez** [comment]
Windows ARM variant marked experimental in #796
